import os
import contextvars
import json
import re
from typing import Optional, Dict, Any
from .client import ArgusClient, AsyncArgusClient
from .exceptions import ArgusException

_current_session = contextvars.ContextVar("argus_session", default=None)


class LocalClientWrapper:
    def __init__(self, engine, manifest_holder):
        self.engine = engine
        self.manifest_holder = manifest_holder

    def extract_intent(self, user_prompt: str, user_id: Optional[str] = None) -> Dict[str, Any]:
        res = self.engine.extract_intent(user_prompt)
        self.manifest_holder.manifest = res.get("manifest")
        self.manifest_holder.session_id = res.get("session_id")
        return res

    def evaluate_action(
        self,
        session_id: str,
        action_type: str,
        target: str,
        target_type: str = "api",
        parameters: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        return self.engine.evaluate_action(
            self.manifest_holder.manifest or {},
            action_type,
            target,
            target_type,
            parameters or {},
        )

    def close(self):
        pass


class AsyncLocalClientWrapper:
    def __init__(self, engine, manifest_holder):
        self.engine = engine
        self.manifest_holder = manifest_holder

    async def extract_intent(self, user_prompt: str, user_id: Optional[str] = None) -> Dict[str, Any]:
        res = self.engine.extract_intent(user_prompt)
        self.manifest_holder.manifest = res.get("manifest")
        self.manifest_holder.session_id = res.get("session_id")
        return res

    async def evaluate_action(
        self,
        session_id: str,
        action_type: str,
        target: str,
        target_type: str = "api",
        parameters: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        return self.engine.evaluate_action(
            self.manifest_holder.manifest or {},
            action_type,
            target,
            target_type,
            parameters or {},
        )

    async def close(self):
        pass


def _parse_scope_to_targets(scope) -> list:
    if not scope:
        return []

    # If it is already a dict or list
    if isinstance(scope, dict):
        targets = []
        for val in scope.values():
            targets.extend(_parse_scope_to_targets(val))
        return targets

    if isinstance(scope, list):
        targets = []
        for val in scope:
            targets.extend(_parse_scope_to_targets(val))
        return targets

    # It must be a string
    scope_str = str(scope).strip()
    if not scope_str:
        return []

    # 1. Try JSON parsing
    try:
        parsed = json.loads(scope_str)
        if isinstance(parsed, (dict, list)):
            return _parse_scope_to_targets(parsed)
    except Exception:
        pass

    # 2. Key-value and word extraction
    targets = []
    # Split by comma or semicolon
    raw_parts = re.split(r'[,;]', scope_str)
    for part in raw_parts:
        part = part.strip()
        if not part:
            continue
        if ':' in part or '=' in part:
            subparts = re.split(r'[:=]', part, maxsplit=1)
            val = subparts[1].strip().strip("'\"")
            if val:
                targets.append(val.lower())
        else:
            part_cleaned = part.strip("'\"")
            if part_cleaned:
                targets.append(part_cleaned.lower())

    # Add the entire original scope string (lowercased, stripped of quotes)
    cleaned_original = scope_str.strip("'\"").lower()
    if cleaned_original not in targets:
        targets.append(cleaned_original)

    # 3. Extract words that look like filenames (contain dots)
    for word in re.split(r'[\s\'",;=:]', scope_str):
        word = word.strip()
        if '.' in word and not word.startswith('.') and not word.endswith('.'):
            cleaned_word = os.path.basename(word).lower()
            if cleaned_word not in targets:
                targets.append(cleaned_word)

    # De-duplicate
    seen = set()
    unique_targets = []
    for t in targets:
        t_clean = t.strip().lower()
        if t_clean and t_clean not in seen:
            seen.add(t_clean)
            unique_targets.append(t_clean)

    return unique_targets


def _verify_manifest_signature(manifest: Optional[Dict[str, Any]]) -> None:
    """
    Verifies that the Intent Manifest has a valid HMAC-SHA256 cryptographic signature
    generated by the ARGUS backend.
    """
    if not manifest:
        return

    # In local mode, or if local bypass is configured, we skip signature checks
    if os.getenv("ARGUS_LOCAL_MODE", "").lower() == "true":
        return

    signature = manifest.get("signature")
    if not signature:
        raise ArgusException(
            "Security Exception: Intent Manifest is unsigned. Cryptographic signature is required in production."
        )

    import hmac
    import hashlib
    import json

    secret_key = os.getenv("ARGUS_SIGNING_KEY")
    if not secret_key:
        if os.getenv("DEMO_MODE", "true").lower() == "false":
            raise ArgusException(
                "Security Exception: ARGUS_SIGNING_KEY must be configured in production mode."
            )
        secret_key = "argus-default-secret-key-for-manifest-signing"
    # Clean dictionary by removing the signature field itself
    clean_dict = {k: v for k, v in manifest.items() if k != "signature"}
    serialized = json.dumps(clean_dict, sort_keys=True).encode('utf-8')
    expected = hmac.new(secret_key.encode(), serialized, hashlib.sha256).hexdigest()

    if not hmac.compare_digest(expected, signature):
        raise ArgusException(
            "Security Exception: Intent Manifest signature verification failed. The manifest has been tampered with."
        )


class Session:
    def __init__(
        self,
        user_prompt: str,
        user_id: Optional[str] = None,
        client: Optional[ArgusClient] = None,
        local_mode: Optional[bool] = None,
    ):
        self.user_prompt = user_prompt
        self.user_id = user_id
        self.session_id: Optional[str] = None
        self.manifest: Optional[Dict[str, Any]] = None
        self._token = None
        self.quarantined = False

        # Check local mode: explicit parameter or ARGUS_LOCAL_MODE env var
        self.local_mode = local_mode if local_mode is not None else (
            os.getenv("ARGUS_LOCAL_MODE", "").lower() == "true"
        )

        if self.local_mode:
            from .local_engine import LocalEvaluationEngine
            self.local_engine = LocalEvaluationEngine()
            self.client = LocalClientWrapper(self.local_engine, self)
        else:
            self.client = client or ArgusClient()

    def local_preflight_check(self, action_type: str, target: str, target_type: str = "api") -> Optional[Dict[str, Any]]:
        import os
        if not self.manifest:
            return None
            
        scope = self.manifest.get("scope")
        allowed_actions = self.manifest.get("allowed_actions", [])
        
        if action_type not in allowed_actions:
            return {
                "decision": "QUARANTINE",
                "reason": f"Local Preflight Block: Action '{action_type}' not authorized in allowed actions {allowed_actions}."
            }
            
        if scope:
            allowed_files = _parse_scope_to_targets(scope)
            target_normalized = os.path.basename(target).lower()
            is_traversal = ".." in target or "/" in target or "\\" in target
            
            matches_scope = False
            for allowed in allowed_files:
                if target_normalized == allowed:
                    if not is_traversal:
                        matches_scope = True
                        break
                        
            if not matches_scope:
                return {
                    "decision": "QUARANTINE",
                    "reason": f"Local Preflight Block: Target '{target}' falls outside the allowed session manifest scope."
                }
                
        return None

    def __enter__(self):
        response = self.client.extract_intent(self.user_prompt, self.user_id)
        self.session_id = response.get("session_id")
        self.manifest = response.get("manifest")
        # Validate Intent Manifest Cryptographic Signature locally (AWT Pattern)
        _verify_manifest_signature(self.manifest)
        self._token = _current_session.set(self)
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if self._token:
            _current_session.reset(self._token)
        self.client.close()


class AsyncSession:
    def __init__(
        self,
        user_prompt: str,
        user_id: Optional[str] = None,
        client: Optional[AsyncArgusClient] = None,
        local_mode: Optional[bool] = None,
    ):
        self.user_prompt = user_prompt
        self.user_id = user_id
        self.session_id: Optional[str] = None
        self.manifest: Optional[Dict[str, Any]] = None
        self._token = None
        self.quarantined = False

        # Check local mode: explicit parameter or ARGUS_LOCAL_MODE env var
        self.local_mode = local_mode if local_mode is not None else (
            os.getenv("ARGUS_LOCAL_MODE", "").lower() == "true"
        )

        if self.local_mode:
            from .local_engine import LocalEvaluationEngine
            self.local_engine = LocalEvaluationEngine()
            self.client = AsyncLocalClientWrapper(self.local_engine, self)
        else:
            self.client = client or AsyncArgusClient()

    def local_preflight_check(self, action_type: str, target: str, target_type: str = "api") -> Optional[Dict[str, Any]]:
        import os
        if not self.manifest:
            return None
            
        scope = self.manifest.get("scope")
        allowed_actions = self.manifest.get("allowed_actions", [])
        
        if action_type not in allowed_actions:
            return {
                "decision": "QUARANTINE",
                "reason": f"Local Preflight Block: Action '{action_type}' not authorized in allowed actions {allowed_actions}."
            }
            
        if scope:
            allowed_files = _parse_scope_to_targets(scope)
            target_normalized = os.path.basename(target).lower()
            is_traversal = ".." in target or "/" in target or "\\" in target
            
            matches_scope = False
            for allowed in allowed_files:
                if target_normalized == allowed:
                    if not is_traversal:
                        matches_scope = True
                        break
                        
            if not matches_scope:
                return {
                    "decision": "QUARANTINE",
                    "reason": f"Local Preflight Block: Target '{target}' falls outside the allowed session manifest scope."
                }
                
        return None

    async def __aenter__(self):
        response = await self.client.extract_intent(self.user_prompt, self.user_id)
        self.session_id = response.get("session_id")
        self.manifest = response.get("manifest")
        # Validate Intent Manifest Cryptographic Signature locally (AWT Pattern)
        _verify_manifest_signature(self.manifest)
        self._token = _current_session.set(self)
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if self._token:
            _current_session.reset(self._token)
        await self.client.close()


def get_current_session() -> Optional[Session | AsyncSession]:
    return _current_session.get()
